### PR TITLE
Update GPU page

### PR DESCRIPTION
**Pull request by kevinstratford**
Please can someone (and preferrably more than one person) look at this closely before taking the PR.

There is a placeholder for a page to discuss ML stuff which it would be good to have before too long.

### CODE REVIEW

**Review by mbareford — COMMENTED** [review]
I don't understand the "nvidia/nvhpc*" modules. All four of them point to cuda-10.2 and mathlibs-10.2. Shouldn't it be 11.2? Also, "nvhpc/21.2" is the same as "nvhpc/21.2-gnu" as they both link to "openmpi-3.1.5-gnu".

Typo in Hardware details, see "archetecture".
Typo in "...the recommended way to view this file is to download[ed] the Nsight Compute...".

**Comment by kevinstratford** [comment]
There's a default set at install time reflected in:
```
$ ls -l /lustre/sw/nvidia/hpcsdk-212/Linux_x86_64/21.2/cuda
total 12
drwxr-xr-x  7 cse y07 4096 Feb 15  2021 10.2
drwxr-xr-x 12 cse y07 4096 Feb 15  2021 11.0
drwxr-xr-x 12 cse y07 4096 Feb 15  2021 11.2
lrwxrwxrwx  1 cse y07    8 Apr  1 15:51 bin -> 10.2/bin
lrwxrwxrwx  1 cse y07   12 Apr  1 15:51 include -> 10.2/include
lrwxrwxrwx  1 cse y07   10 Apr  1 15:51 lib64 -> 10.2/lib64
lrwxrwxrwx  1 cse y07    9 Apr  1 15:51 nvvm -> 10.2/nvvm
```
It's not clear to me there's any simple way around this to get at the non-default versions.

We may need to move to something like:
```
nvidia/nvhpc/21.9/cuda-11.4 (default)
nvidia/nvhpc/21.9/cuda-11.0
nvidia/nvhpc/21.9/cuda-10.2
```
to cover the three possible toolchains available.

**Comment by mbareford** [comment]
Yes, I agree, adding "nvidia/nvhpc/21.9/cuda-X.Y" modules is the best way forward.

**Comment by kevinstratford** [comment]
I'm going to push this out now, and add a new issue to tackle CUDA versions.

**Pull request merged**
