### PR TITLE
Update SAFE documentation links to point to new Cirrus-specific docs

### PR DESCRIPTION
**Pull request by jamesp-epcc**

### CODE REVIEW

**Comment by aturner-epcc** [comment]
@jamesp-epcc These links are not general, they are for industry only so we will not be changing the Cirrus docs in this way.

Any other comments before I close this?

**Comment by jamesp-epcc** [comment]
@aturner-epcc George G has requested that the SAFE documentation linked from the Cirrus documentation should be Cirrus-only rather than mentioning Tier2, therefore I created a Cirrus-specific version of the SAFE documentation. Was this not the right thing to do? I'm sure it's been discussed at meetings etc.

**Comment by aturner-epcc** [comment]
@jamesp-epcc The problem here is that only some of the Cirrus users (industry users) will be using the Cirrus-specific SAFE. Our standard academic users will be using the Tier-2 SAFE - which at some point will probably become a unified ARCHER2 and Tier-2 SAFE. This is part of a wider strategy to integrate UK HPC more closely.

Linking to a SAFE that is not relevant to them from the docs will just cause confusion. Hence, I want to reject this PR.

**Comment by jamesp-epcc** [comment]
@aturner-epcc OK.

**Pull request closed without merging**
