### PR TITLE
Mbareford/namd update

### PR DESCRIPTION
**Pull request by mbareford**

### CODE REVIEW

**Comment by mbareford** [comment]
Please could someone check that the namd submission scripts make sense. I've tested the scripts using the alanin and stmv benchmarks and the namd code runs without error, but it might be that the job could have been run more efficiently.

**Comment by kevinstratford** [comment]
By inspection, I'd say they were ok.

**Comment by kevinstratford** [comment]
It looks like NAMD GPU jobs are limited to a single node. Correct?

**Comment by mbareford** [comment]
The NAMD GPU job is being run as one task with 40 threads that are assigned to the 4 GPUs in a round robin fashion. There's nothing restricting you to one GPU node; you should be able to run with two tasks occupying separate GPU nodes.

**Comment by mbareford** [comment]
I'll add some more explanation to the GPU script and give an example that works on 2 GPU nodes.

**Comment by mbareford** [comment]
It seems that the NAMD GPU can only make use of one GPU. Any attempt to use more devices merely replicates the job for each extra GPU. I've updated the job script so that only one GPU is specified. This will need to be investigated after the Cirrus rebuild.

**Pull request merged**
