### PR TITLE
Update python.rst

### PR DESCRIPTION
**Pull request by wood-chris**
Adding info about how to run Jupyter Notebooks on Cirrus

### CODE REVIEW

**Review by kevinstratford — CHANGES_REQUESTED** [review]
Following discussion we'll put this on hold until a working solution is identified.

**Comment by wood-chris** [comment]
We think maybe the SSH changes have added a complication which wasn't there before....

**Comment by wood-chris** [comment]
Typo fixed, but 403 error unreproducible

**Comment by wood-chris** [comment]
@kevinstratford (+ @aturner-epcc?) I've also had reports that MobaXTerm users have difficulty with these instructions... maybe I could ask George B to see if they work for him

**Review by aturner-epcc — APPROVED** [review]
LGTM

**Pull request merged**
